INSERT INTO ORGAN_MELDUJACY (KOD_ORGANU, NAZWA_ORGANU) VALUES ('1', 'Urząd Miejski w Baborowie');
INSERT INTO ORGAN_MELDUJACY (KOD_ORGANU, NAZWA_ORGANU) VALUES ('2', 'Urząd Miejski w Białej');
INSERT INTO ORGAN_MELDUJACY (KOD_ORGANU, NAZWA_ORGANU) VALUES ('3', 'Urząd Gminy Branice');
INSERT INTO ORGAN_MELDUJACY (KOD_ORGANU, NAZWA_ORGANU) VALUES ('4', 'Urząd Miasta w Brzegu');
INSERT INTO ORGAN_MELDUJACY (KOD_ORGANU, NAZWA_ORGANU) VALUES ('5', 'Urząd Miejski w Byczynie');

INSERT INTO ORGAN_NADAJACY (KOD_ORGANU, NAZWA_ORGANU) VALUES ('1', 'Urząd Gminy Chrząstowice ');
INSERT INTO ORGAN_NADAJACY (KOD_ORGANU, NAZWA_ORGANU) VALUES ('2', 'Urząd Gminy Cisek');
INSERT INTO ORGAN_NADAJACY (KOD_ORGANU, NAZWA_ORGANU) VALUES ('3', 'Urząd Gminy Dąbrowa');
INSERT INTO ORGAN_NADAJACY (KOD_ORGANU, NAZWA_ORGANU) VALUES ('4', 'Urząd Miejski w Dobrodzieniu');
INSERT INTO ORGAN_NADAJACY (KOD_ORGANU, NAZWA_ORGANU) VALUES ('5', 'Urząd Gminy Dobrzeń Wielki');