CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;
CREATE MEMORY TABLE "PUBLIC"."ADRES"(
    "ID" BIGINT NOT NULL,
    "KOD_POCZTOWY" VARCHAR(255),
    "MIEJSCOWOSC" VARCHAR(255),
    "NUMER_DOMU" VARCHAR(255),
    "NUMER_MIESZKANIA" VARCHAR(255),
    "ULICA" VARCHAR(255),
    "FK_ORGAN_MELDUJACY" BIGINT,
    "OSOBA_ID" BIGINT
);

ALTER TABLE "PUBLIC"."ADRES" ADD CONSTRAINT "PUBLIC"."PK_ADRES" PRIMARY KEY("ID");

CREATE MEMORY TABLE "PUBLIC"."ADRES_TO_HISTORYCZNE"(
    "ADRES_ID" BIGINT NOT NULL,
    "HISTORYCZNE_NAZWY_ULIC_ID" BIGINT NOT NULL
);

CREATE MEMORY TABLE "PUBLIC"."DANE_IMION"(
    "ID" BIGINT NOT NULL,
    "IMIE_DRUGIE" VARCHAR(255),
    "IMIE_PIERWSZE" VARCHAR(255) NOT NULL,
    "IMIONA_KOLEJNE" VARCHAR(255),
    "FK_ORGAN_NADAJACY" BIGINT NOT NULL
);

ALTER TABLE "PUBLIC"."DANE_IMION" ADD CONSTRAINT "PUBLIC"."PK_DANE_IMION" PRIMARY KEY("ID");

CREATE MEMORY TABLE "PUBLIC"."HISTORYCZNE_NAZWY_ULIC"(
    "ID" BIGINT NOT NULL,
    "NOWA_NAZWA" VARCHAR(255) NOT NULL,
    "STARA_NAZWA" VARCHAR(255) NOT NULL
);

ALTER TABLE "PUBLIC"."HISTORYCZNE_NAZWY_ULIC" ADD CONSTRAINT "PUBLIC"."PK_HISTORYCZNE_NAZWY_ULIC" PRIMARY KEY("ID");

CREATE MEMORY TABLE "PUBLIC"."ORGAN_MELDUJACY"(
    "KOD_ORGANU" BIGINT NOT NULL,
    "NAZWA_ORGANU" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."ORGAN_MELDUJACY" ADD CONSTRAINT "PUBLIC"."PK_ORGAN_MELDUJACY" PRIMARY KEY("KOD_ORGANU");

CREATE MEMORY TABLE "PUBLIC"."ORGAN_NADAJACY"(
    "KOD_ORGANU" BIGINT NOT NULL,
    "NAZWA_ORGANU" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."ORGAN_NADAJACY" ADD CONSTRAINT "PUBLIC"."PK_ORGAN_NADAJACY" PRIMARY KEY("KOD_ORGANU");

CREATE MEMORY TABLE "PUBLIC"."OSOBA"(
    "ID" BIGINT NOT NULL,
    "CZY_ZYJE" BOOLEAN NOT NULL,
    "PESEL" VARCHAR(255) NOT NULL,
    "DANE_IMION_ID" BIGINT NOT NULL
);

ALTER TABLE "PUBLIC"."OSOBA" ADD CONSTRAINT "PUBLIC"."PK_OSOBA" PRIMARY KEY("ID");

ALTER TABLE "PUBLIC"."ADRES" ADD CONSTRAINT "PUBLIC"."FK_ADRES_ORGAN_MELDUJACY" FOREIGN KEY("FK_ORGAN_MELDUJACY") REFERENCES "PUBLIC"."ORGAN_MELDUJACY"("KOD_ORGANU") NOCHECK;

ALTER TABLE "PUBLIC"."ADRES_TO_HISTORYCZNE" ADD CONSTRAINT "PUBLIC"."FK_HISTORYCZNE_NAZWY_ULIC_ID" FOREIGN KEY("HISTORYCZNE_NAZWY_ULIC_ID") REFERENCES "PUBLIC"."HISTORYCZNE_NAZWY_ULIC"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ADRES_TO_HISTORYCZNE" ADD CONSTRAINT "PUBLIC"."FK_ADRES_ID" FOREIGN KEY("ADRES_ID") REFERENCES "PUBLIC"."ADRES"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DANE_IMION" ADD CONSTRAINT "PUBLIC"."FKIVE8HR0UEKN8LMVWDDF8XJRM4" FOREIGN KEY("FK_ORGAN_NADAJACY") REFERENCES "PUBLIC"."ORGAN_MELDUJACY"("KOD_ORGANU") NOCHECK;

ALTER TABLE "PUBLIC"."ADRES" ADD CONSTRAINT "PUBLIC"."FK_ADRES_OSOBA" FOREIGN KEY("OSOBA_ID") REFERENCES "PUBLIC"."OSOBA"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."OSOBA" ADD CONSTRAINT "PUBLIC"."FK_OSOBA_DANE_IMION" FOREIGN KEY("DANE_IMION_ID") REFERENCES "PUBLIC"."DANE_IMION"("ID") NOCHECK;